# Number of days of inactivity before an issue becomes stale
daysUntilStale: 45
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - StaleBot Ignore
# Label to use when marking an issue as stale
staleLabel: Stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale as there has not been any
  activity for sometime. The issue will be closed in 14 days if no further activity. 
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: Closed by Stale Bot due to no activity on issue.