---
# Configuration file for pre-commit (https://pre-commit.com/)

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ea782651a7e32f40a3d13b76c79d5a2474ee8723 # v2.5.1
    hooks:
      - id: prettier
        stages: [commit]
        language_version: system

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: 81c4cafc55d9f3da32b88aaad05ffb50a52ddfb2 # v0.8.0
    hooks:
      - id: shellcheck
        stages: [commit]

  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: 148ec47877499e3d671f6366f9eed812db181b40 # v1.2.0
    hooks:
      - id: nixpkgs-fmt
        stages: [commit]
