---
# Configuration file for pre-commit (https://pre-commit.com/)

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ea782651a7e32f40a3d13b76c79d5a2474ee8723 # v2.5.1
    hooks:
      - id: prettier
        stages: [commit]
        language_version: system
