# See https://docs.travis-ci.com/

#os: trusty
language: perl

matrix:

  include:

  # Oldest supported versions
  - env: PGSQL=9.3 PGIS=2.2 TABLEVERSION_BRANCH=release-1.5 DBPATCH_BRANCH=release-1.3
    perl: 5.12
    addons:
      postgresql: 9.3
      apt:
        packages:
        - postgresql-9.3
        - postgresql-9.3-pgtap
        - postgresql-server-dev-9.3
        - postgresql-9.3-postgis-2.2
        - postgresql-9.3-postgis-2.2-scripts
        - pgxnclient
        - debhelper
        - fakeroot

  # Found in bde-processor-deployment
  - env: PGSQL=9.3 PGIS=2.2 TABLEVERSION_BRANCH=release-1.5 DBPATCH_BRANCH=release-1.3
    perl: 5.18
    addons:
      postgresql: 9.3
      apt:
        packages:
        - postgresql-9.3
        - postgresql-9.3-pgtap
        - postgresql-server-dev-9.3
        - postgresql-9.3-postgis-2.2
        - postgresql-9.3-postgis-2.2-scripts
        - pgxnclient
        - debhelper
        - fakeroot

  # Found on Debian GNU/Linux 8.8 (jessie)
  - env: PGSQL=9.4 PGIS=2.3 TABLEVERSION_BRANCH=release-1.5 DBPATCH_BRANCH=release-1.3
    perl: 5.20
    addons:
      postgresql: 9.4
      apt:
        packages:
        - postgresql-9.4
        - postgresql-9.4-pgtap
        - postgresql-server-dev-9.4
        - postgresql-9.4-postgis-2.3
        - postgresql-9.4-postgis-2.3-scripts
        - pgxnclient
        - debhelper
        - fakeroot

  # Found on Ubuntu 16.04.3 LTS
  - env: PGSQL=9.5 PGIS=2.2 TABLEVERSION_BRANCH=release-1.5 DBPATCH_BRANCH=release-1.3
    perl: 5.22
    addons:
      postgresql: 9.5
      apt:
        packages:
        - postgresql-9.5
        - postgresql-9.5-pgtap
        - postgresql-server-dev-9.5
        - postgresql-9.5-postgis-2.2
        - postgresql-9.5-postgis-2.2-scripts
        - pgxnclient
        - debhelper
        - fakeroot

  # Found on Debian GNU/Linux 8.5 (jessie-backports)
  - env: PGSQL=9.6 PGIS=2.3 TABLEVERSION_BRANCH=release-1.5 DBPATCH_BRANCH=release-1.3
    perl: 5.20
    addons:
      postgresql: 9.6
      apt:
        packages:
        - postgresql-9.6
        - postgresql-9.6-pgtap
        - postgresql-server-dev-9.6
        - postgresql-9.6-postgis-2.3
        - postgresql-9.6-postgis-2.3-scripts
        - pgxnclient
        - debhelper
        - fakeroot

  # Found on Ubuntu 17.04
  - env: PGSQL=9.6 PGIS=2.3 TABLEVERSION_BRANCH=master DBPATCH_BRANCH=master STDOUT_SCHEMA_LOADING_SUPPORTED=1
    perl: 5.24
    addons:
      postgresql: 9.6
      apt:
        packages:
        - postgresql-9.6
        - postgresql-9.6-pgtap
        - postgresql-server-dev-9.6
        - postgresql-9.6-postgis-2.3
        - postgresql-9.6-postgis-2.3-scripts
        - pgxnclient
        - debhelper
        - fakeroot

  # Found on Ubuntu 18.04
  - env: PGSQL=10 PGIS=2.4 TABLEVERSION_BRANCH=master DBPATCH_BRANCH=master STDOUT_SCHEMA_LOADING_SUPPORTED=1
    perl: 5.26
    addons:
      postgresql: 10
      apt:
        packages:
        - postgresql-10
        - postgresql-10-pgtap
        - postgresql-server-dev-10
        - postgresql-10-postgis-2.4
        - postgresql-10-postgis-2.4-scripts
        - pgxnclient
        - debhelper
        - fakeroot

before_install:
  - pg_config --version
  # Install packages needed for testing
  - cpanm Test::Cmd Test::Exception
  # Install dbpatch PostgreSQL extension
  - pushd /tmp
  - wget -q -O -
    https://github.com/linz/postgresql-dbpatch/archive/${DBPATCH_BRANCH}.tar.gz
    | tar xzf - && cd postgresql-dbpatch-${DBPATCH_BRANCH}
  - sudo env "PATH=$PATH" make install
  - popd
  # Install table_version PostgreSQL extension
  - pushd /tmp
  - wget -q -O -
    https://github.com/linz/postgresql-tableversion/archive/${TABLEVERSION_BRANCH}.tar.gz
    | tar vxzf - && cd postgresql-tableversion-${TABLEVERSION_BRANCH}
  - sudo env "PATH=$PATH" make install
  - popd
  # Install pgtap PostgreSQL extension
  - sudo env "PATH=$PATH" pgxn install pgtap
  # Install LINZ::Config
  - pushd /tmp
  - wget
    https://github.com/linz/linz_utils_perl/archive/1.0.1.tar.gz
  - tar xzf 1.0.1.tar.gz
  - cd linz_utils_perl-1.0.1
  - perl Build.PL
  - sudo env "PATH=$PATH" ./Build install
  - popd
  # Install LINZ::Bde
  - pushd /tmp
  - wget https://github.com/linz/linz-bde-perl/archive/1.0.2.tar.gz
  - tar xzf 1.0.2.tar.gz && cd linz-bde-perl-1.0.2
  - perl Build.PL
  - sudo env "PATH=$PATH" ./Build install
  - popd
  # Install linz-bde-schema
  - pushd /tmp
  - wget -q -O -
    https://github.com/linz/linz-bde-schema/archive/1.2.1.tar.gz
    | tar xzf - && cd linz-bde-schema-1.2.1
  - sudo env "PATH=$PATH" make install
  - popd
  # Install linz-bde-copy
  - pushd /tmp
  - wget -q -O -
    https://github.com/linz/linz-bde-copy/archive/1.2.1.tar.gz
    | tar xzf - && cd linz-bde-copy-1.2.1
  - cmake .
  - make && sudo env "PATH=$PATH" make install
  - popd

script:
  - ./configure
  - make check
  - make dist
  - make distcheck
  # Test building deb package
  - git clean -dxf && dpkg-buildpackage -d -b -uc -us
