# See https://docs.travis-ci.com/

dist: bionic
language: perl

global:

    - STDOUT_SCHEMA_LOADING_SUPPORTED: 1

matrix:

  include:

  # Found on Ubuntu 18.04 (bionic)
  - env: PGSQL=10 PGIS=2.4 TABLEVERSION_BRANCH=release-1.6 DBPATCH_BRANCH=release-1.4
    perl: 5.26

  # Found on Ubuntu 18.04 (bionic)
  - env: PGSQL=10 PGIS=2.4 TABLEVERSION_BRANCH=master DBPATCH_BRANCH=master
    perl: 5.26

before_install:
  # Purge PostgreSQL packages
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5
    postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  # Install packages
  - sudo apt-get install -y
    postgresql-${PGSQL}
    postgresql-${PGSQL}-pgtap
    postgresql-server-dev-${PGSQL}
    postgresql-${PGSQL}-postgis-${PGIS}
    postgresql-${PGSQL}-postgis-${PGIS}-scripts
    pgxnclient
    debhelper
    fakeroot
  - pg_config --version
  - export PATH=/usr/lib/postgresql-${PGSQL}/bin:$PATH
  - sudo -u postgres env "PATH=$PATH" createuser -s "$USER"
  - sudo -u postgres env "PATH=$PATH" createuser -s root
  # Install packages needed for testing
  - cpanm Test::Cmd Test::Exception
  # Install dbpatch PostgreSQL extension
  - pushd /tmp
  - wget -q -O -
    https://github.com/linz/postgresql-dbpatch/archive/${DBPATCH_BRANCH}.tar.gz
    | tar xzf - && cd postgresql-dbpatch-${DBPATCH_BRANCH}
  - sudo env "PATH=$PATH" make install
  - popd
  # Install table_version PostgreSQL extension
  - pushd /tmp
  - wget -q -O -
    https://github.com/linz/postgresql-tableversion/archive/${TABLEVERSION_BRANCH}.tar.gz
    | tar vxzf - && cd postgresql-tableversion-${TABLEVERSION_BRANCH}
  - make
  - sudo env "PATH=$PATH" make install
  - popd
  # Install pgtap PostgreSQL extension
  - sudo env "PATH=$PATH" pgxn install pgtap
  # Install LINZ::Config
  - pushd /tmp
  - wget
    https://github.com/linz/linz_utils_perl/archive/1.0.1.tar.gz
  - tar xzf 1.0.1.tar.gz
  - cd linz_utils_perl-1.0.1
  - perl Build.PL
  - sudo env "PATH=$PATH" ./Build install
  - popd
  # Install LINZ::Bde
  - pushd /tmp
  - wget https://github.com/linz/linz-bde-perl/archive/1.0.2.tar.gz
  - tar xzf 1.0.2.tar.gz && cd linz-bde-perl-1.0.2
  - perl Build.PL
  - sudo env "PATH=$PATH" ./Build install
  - popd
  # Install linz-bde-schema
  - pushd /tmp
  - wget -q -O -
    https://github.com/linz/linz-bde-schema/archive/1.2.1.tar.gz
    | tar xzf - && cd linz-bde-schema-1.2.1
  - sudo env "PATH=$PATH" make install
  - popd
  # Install linz-bde-copy
  - pushd /tmp
  - wget -q -O -
    https://github.com/linz/linz-bde-copy/archive/1.2.1.tar.gz
    | tar xzf - && cd linz-bde-copy-1.2.1
  - cmake .
  - make && sudo env "PATH=$PATH" make install
  - popd

script:
  - ./configure
  - make check
  - make dist
  - make distcheck
  # Test building deb package
  - git clean -dxf && dpkg-buildpackage -d -b -uc -us
