# See https://docs.travis-ci.com/

#os: trusty
language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"

services:
  - postgresql: "9.4"

addons:
  apt:
    packages:
    - postgresql-9.4
    - postgresql-server-dev-9.4
    - pgxnclient

before_install:
  # Install packages needed for testing
  - sudo apt-get install
    debhelper
    fakeroot
  - cpanm Test::Cmd Test::Exception
  # Install dbpatch PostgreSQL extension
  - sudo pgxn install dbpatch
  # Install table_version PostgreSQL extension
  - sudo pgxn install table_version
  # Install LINZ::Config
  - pushd /tmp
  - wget
    https://github.com/linz/linz_utils_perl/archive/1.0.1.tar.gz
  - tar xzf 1.0.1.tar.gz
  - cd linz_utils_perl-1.0.1
  - perl Build.PL
  - sudo ./Build install
  - popd
  # Install LINZ::Bde
  - pushd /tmp
  - wget https://github.com/linz/linz_bde_perl/archive/1.0.2.tar.gz
  - tar xzf 1.0.2.tar.gz && cd linz_bde_perl-1.0.2
  - perl Build.PL
  - sudo ./Build install
  - popd
  # Install linz-bde-schema
  - pushd /tmp
  - wget -q -O - 
    https://github.com/linz/linz-bde-schema/archive/1.0.2.tar.gz
    | tar xzf - && cd linz-bde-schema-1.0.2
  - sudo make install
  - popd
  # Install linz_bde_copy
  - pushd /tmp
  - wget -q -O -
    https://github.com/linz/linz_bde_copy/archive/1.2.1.tar.gz
    | tar xzf - && cd linz_bde_copy-1.2.1
  - cmake .
  - make && sudo make install
  - popd

script:
  - ./configure
  - make test
  - make dist
  - make distcheck
  # Test building deb package
  - git clean -dxf && dpkg-buildpackage -d -b -uc -us
