#!/bin/bash

set -e

SCRIPT=${0##*/}
SUCCESS=0
FAILURE=1

clean_up()
{
    [ -f $TMPFILE ] && rm -f $TMPFILE
}

die()
{
    msg=$1
    err_no=$2
    echo "$SCRIPT: $msg" 1>&2
    clean_up
    exit ${err_no:-$FAILURE}
}

# Make sure the database is installed and running.

LDS_PACKAGE=linz-bde-uploader
LDS_SHARE_DIR=/usr/share/$LDS_PACKAGE
LDS_LOG_DIR=/var/log/$LDS_PACKAGE
LDS_USER=lds_bde
PG_USER=postgres
DB=bde_db
PG_SERVICE=postgresql
PG_INIT=/etc/init.d/$PG_SERVICE
USE_SERVICE=0
HAS_POSTGIS_EXT=
HAS_ADMIN_EXT=
TMPFILE=`mktemp -t $LDS_PACKAGE.XXXXXX` || { echo "$0: Cannot create temporary file" >&2; exit 1;  }
chmod 0777 $TMPFILE

if [ -x /usr/sbin/service ]; then
    USE_SERVICE=1
fi

if [ ! -x $PG_INIT ]; then
    die "Can not find $PG_INIT init script"
fi

if [ $USE_SERVICE ]; then
  cmd="service $PG_SERVICE status"
else
  cmd="$PG_INIT status"
fi
$cmd
rc=$?
if [ $rc -ne $SUCCESS ]; then
    if [ $USE_SERVICE ]; then
        cmd="service $PG_SERVICE start"
    else
        cmd="$PG_INIT start"
    fi
    $cmd
    rc=$?
    if [ $rc -ne $SUCCESS ]; then
      die "There was a problem starting the $PG_SERVICE service"
    fi
fi

PG_VERSION="$(su -l $PG_USER -c """psql -t -A postgres -c 'SHOW server_version_num'""")"
    
# create bde database if it does not exists
if ! su -l $PG_USER -c "psql -t -A --list | grep $DB"; then
    rc=$(sudo su -l $PG_USER -c "createdb -O $PG_USER -E UTF8 -T template0 -l C $DB &> $TMPFILE; echo \$?")
    if [ $rc -ne $SUCCESS ] ; then
        die "Could not create database" $rc
    fi
    
    rc=$(sudo su -l $PG_USER -c "createlang plperlu $DB &> $TMPFILE; echo \$?")
    if [ $rc -ne $SUCCESS ] ; then
        die "Could not install plperlu database language" $rc
    fi
    
    rc=$(sudo su -l $PG_USER -c "createlang plperl $DB &> $TMPFILE; echo \$?")
    if [ $rc -ne $SUCCESS ] ; then
        die "Could not install plperl database language" $rc
    fi
    
    if [ $PG_VERSION -gt 90100 ]; then
        HAS_POSTGIS_EXT="$(su -l $PG_USER -c """psql -t -A -c 'SELECT name FROM pg_available_extensions WHERE name = \$\$postgis\$\$' $PG_USER""")"
        HAS_ADMIN_EXT="$(su -l $PG_USER -c """psql -t -A -c 'SELECT name FROM pg_available_extensions WHERE name = \$\$adminpack\$\$' $PG_USER""")"
    fi
    
    if [ -n "$HAS_ADMIN_EXT" ]; then
        rc=$(sudo su -l $PG_USER -c "psql -d $DB -c 'CREATE EXTENSION adminpack' &> $TMPFILE; echo \$?")
        if [ $rc -ne $SUCCESS ] ; then
            die "Could install adminpack functions" $rc
        fi
    else
        PG_ADMINPACK=/usr/share/postgresql/9.0/contrib/adminpack.sql
        if [ -f $PG_ADMINPACK ]; then
            rc=$(sudo su -l $PG_USER -c "psql -v ON_ERROR_STOP=TRUE -d $DB -f $PG_ADMINPACK &> $TMPFILE; echo \$?")
            if [ $rc -ne $SUCCESS ] ; then
                die "Could not install database admin pack" $rc
            fi
        fi
    fi
    
    if [ -n "$HAS_POSTGIS_EXT" ]; then
        rc=$(sudo su -l $PG_USER -c "psql -d $DB -c 'CREATE EXTENSION postgis' &> $TMPFILE; echo \$?")
        if [ $rc -ne $SUCCESS ] ; then
            die "Could install postgis functions" $rc
        fi
    else
        # install postgis 1.5
        POSTGIS_INSTALL_FILE=/usr/share/postgresql/9.0/contrib/postgis-1.5/postgis.sql
        rc=$(sudo su -l $PG_USER -c "psql -v ON_ERROR_STOP=TRUE -d $DB -f $POSTGIS_INSTALL_FILE &> $TMPFILE; echo \$?")
        if [ $rc -ne $SUCCESS ] ; then
            die "Could install postgis functions" $rc
        fi
        
        POSTGIS_SRS_FILE=/usr/share/postgresql/9.0/contrib/postgis-1.5/postgis.sql
        rc=$(sudo su -l $PG_USER -c "psql -v ON_ERROR_STOP=TRUE -d $DB -f $POSTGIS_SRS_FILE &> $TMPFILE; echo \$?")
        if [ $rc -ne $SUCCESS ] ; then
            die "Could install postgis SRS data" $rc
        fi
    fi
fi

#ensure patches.sql is the last file in this array
SQL_FILES="
    $LDS_SHARE_DIR/sql/bde_roles.sql
    $LDS_SHARE_DIR/sql/bde_schema.sql
    $LDS_SHARE_DIR/sql/bde_functions.sql
    $LDS_SHARE_DIR/sql/table_version_tables.sql
    $LDS_SHARE_DIR/sql/table_version_functions.sql
    $LDS_SHARE_DIR/sql/bde_control_tables.sql
    $LDS_SHARE_DIR/sql/bde_control_functions.sql
    $LDS_SHARE_DIR/sql/lds_layer_tables.sql
    $LDS_SHARE_DIR/sql/lds_layer_functions.sql
    $LDS_SHARE_DIR/sql/bde_ext_schema.sql
    $LDS_SHARE_DIR/sql/bde_ext_functions.sql
    $LDS_SHARE_DIR/sql/create_table_polygon_grid.sql
    $LDS_SHARE_DIR/sql/patch_management.sql
    $LDS_SHARE_DIR/sql/patches.sql
"

for SQL_FILE in $SQL_FILES
do
    rc=$(sudo su -l $PG_USER -c "psql -v ON_ERROR_STOP=TRUE -d $DB -f $SQL_FILE &> $TMPFILE; echo \$?")
    if [ $rc -ne $SUCCESS ] ; then
        cat $TMPFILE
        die "Couldn't install SQL file: $SQL_FILE" $rc
    fi
done

# creating lds user group if it isn't already there
if ! getent group $LDS_USER >/dev/null; then
    addgroup --group $LDS_USER >/dev/null
fi

# creating lds user if he isn't already there
if ! getent passwd $LDS_USER >/dev/null; then
        adduser \
          --system \
          --ingroup $LDS_USER \
          --gecos "LDS BDE Maintainer" \
        $LDS_USER  >/dev/null
fi

if ! su -l $PG_USER -c "psql -t -c \"select 1 from pg_roles where rolname = '$LDS_USER' AND rolcanlogin = TRUE\"" | grep 1; then
    # Create $LDS_USER user without password
    su -l $PG_USER -c "psql -c 'CREATE ROLE $LDS_USER LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE'"
    su -l $PG_USER -c "psql -c 'ALTER ROLE $LDS_USER SET search_path=bde, bde_control, lds, table_version, public'"
    su -l $PG_USER -c "psql -c 'GRANT bde_dba TO $LDS_USER'";
fi;


# now create log directory if it does not exist.
if [ ! -d $LDS_LOG_DIR ]; then
    mkdir -p $LDS_LOG_DIR
fi
chown -R $LDS_USER:adm $LDS_LOG_DIR;
chmod 0755 $LDS_LOG_DIR;

clean_up

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
