---
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # this is to enable gitlint to check all PR commit messages
          submodules: 'true'

      - name: Install Dependencies
        run: sudo snap install pre-commit --classic

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files
