---
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo snap install --classic pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
